### ISSUE TITLE
mint + put on sale

### ISSUE THREAD

**Issue by selimerunkut** [OnBlockIO/GhostMarketContractBSC#21]
Option to mint the NFT and put it on sale in one transaction:

![2021-05-10 19 47 14](https://user-images.githubusercontent.com/31136147/117695075-2820af80-b1c0-11eb-9d07-3f2e8e92f56b.jpg)
![2021-05-10 19 47 27](https://user-images.githubusercontent.com/31136147/117695152-38388f00-b1c0-11eb-94cd-2caa9707d491.jpg)

**Comment by vincentgeneste** [comment]
will be handled on frontend
